// Installed plugin rendering; imported only by the on-demand Settings controller.
import { esc, icon } from "../utils/dom.js";
import { pluginErrors } from "./plugin_api.js";
export const restartTitles = new Set();
const problem = (p) => !["ok", "disabled"].includes(p.status);
const failed = (p, errors = pluginErrors) => problem(p) || errors.some((e) => e.id === p.id);
export const key = (id) => encodeURIComponent(id);
export const title = (p) => p.title || p.id;
const status = (p, errors) => !p.enabled ? ["Off", "muted"] : failed(p, errors) ? ["Error", "fail"] : p.active ? ["Active", "ok"] : ["Restart needed", "warn"];
export function pluginProblems(list, errors = pluginErrors) {
  return [...(list.plugins || []).filter(problem), ...errors.map((p) => ({ ...(list.plugins || []).find((entry) => entry.id === p.id), ...p, status: "browser", error: `browser: ${p.message}` }))];
}
export function renderPlugins(list, canWrite, errors = pluginErrors) {
  const problems = pluginProblems(list, errors);
  return `<div class="set-sec-h"><h3>${icon("metadata")} Plugins</h3><span class="grow"></span><button type="button" class="btn sm" data-plug-refresh>${icon("sync")} Refresh</button></div>
<div data-plug-banner>${list.safe_mode ? '<p class="callout warn" role="status"><b>Safe mode</b>: plugins are not loaded (<code>--safe-mode</code> / <code>ALFRD_NO_PLUGINS</code>).</p>' : ""}${restartTitles.size ? '<p data-restart-placeholder class="callout warn">Restart <code>alfrd serve</code> to load the change.</p>' : ""}</div>
<div data-plug-tools><div class="plug-tabs" role="tablist" aria-label="Plugins"><button class="btn sm" role="tab" id="plug-tab-installed" aria-selected="true" aria-controls="plug-panel-installed" tabindex="0">Installed</button><button class="btn sm" role="tab" id="plug-tab-browse" aria-selected="false" aria-controls="plug-panel-browse" tabindex="-1" data-plug-open>Browse</button></div><div id="plug-panel-browse" role="tabpanel" aria-labelledby="plug-tab-browse" hidden></div></div><div id="plug-panel-installed" role="tabpanel" aria-labelledby="plug-tab-installed" data-plug-installed>
${problems.length ? `<details class="plug-diag" open><summary>${icon("alert")} <b>Diagnostics</b> · ${problems.length} problem${problems.length === 1 ? "" : "s"}</summary>${problems.map((p, i) => `<div class="plug-diag-row" data-plug-diag="${esc(p.id)}"><b>${esc(title(p))}</b><p class="mono small">${esc(p.error || p.status)}</p>${p.missing_bin?.length ? `<p class="small">Install <code>${esc(p.missing_bin.join(", "))}</code> and restart <code>alfrd serve</code>.</p>` : ""}${p.traceback_tail ? `<details><summary>Traceback</summary><pre class="mono small">${esc(p.traceback_tail)}</pre></details>` : ""}<button type="button" class="btn sm" data-plug-copy="${i}">Copy details</button></div>`).join("")}</details>` : ""}
<fieldset class="plug-themes"><legend>Theme</legend><div class="plug-theme-grid">${(list.themes || []).map((t) => `<label class="plug-theme"><input type="radio" name="plug-theme" value="${esc(t.id)}" ${t.id === list.theme ? "checked" : ""} ${canWrite ? "" : "disabled"}><span class="plug-swatch ${t.source === "builtin" ? "plug-swatch-builtin" : ""}" aria-hidden="true"></span><span>${esc(title(t))}<small class="muted">${esc(t.source === "plugin" ? `from plugin ${t.id}` : t.source === "builtin" ? "built-in" : "drop-in")}</small></span><span class="plug-theme-check" aria-hidden="true">${icon("check")}</span></label>`).join("")}</div>${canWrite ? "" : '<small class="muted">Change themes from a browser on the server host.</small>'}</fieldset>
${(list.plugins || []).length ? `<ul class="plug-list">${list.plugins.map((p) => { const [label, tone] = status(p, errors); return `<li class="plug-row"><input type="checkbox" role="switch" class="plug-switch" data-plug-toggle="${esc(p.id)}" aria-label="Enable ${esc(title(p))}" aria-describedby="plug-status-${key(p.id)}" ${p.enabled ? "checked" : ""} ${canWrite && !list.safe_mode ? "" : "disabled"}><div><b>${esc(title(p))}</b> <small class="muted tabular">v${esc(p.version || "")}</small><div class="plug-kinds">${(p.kinds || []).map((kind) => `<span class="badge tone-muted">${esc(kind)}</span>`).join(" ")}</div><small class="muted plug-description">${esc(p.description || "")}</small></div><div class="plug-actions">${p.managed ? `<button class="btn sm ghost" data-plug-more="${esc(p.id)}" aria-haspopup="menu" aria-label="More actions for ${esc(title(p))}">⋯</button>` : ""}${failed(p, errors) ? `<button type="button" data-plug-error="${esc(p.id)}"` : "<span"} id="plug-status-${key(p.id)}" class="badge tone-${tone}">${label}${failed(p, errors) ? "</button>" : "</span>"}</div></li>`; }).join("")}</ul>` : '<div class="empty">No plugins installed.<p><code>alfrd plugin install &lt;wheel or folder&gt;</code> · <a href="https://github.com/avikhagol/alfrd/blob/HEAD/docs/plugins.md" target="_blank" rel="noopener">Learn more</a></p></div>'}
</div><p class="sr-only" role="status" aria-live="polite" data-plug-live></p>`;
}
