[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alfrd"
version = "0.2.1.0"
description = "Automated Logical FRamework for Dynamic script execution (ALFRD)"
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-3-Clause"
authors = [
  { name = "Avinash Kumar", email = "avialxee@gmail.com" }
]
urls = { "Homepage" = "https://github.com/avialxee/alfrd/" }
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Intended Audience :: Science/Research"
]

dependencies = [
  "pandas",
  "numpy",
  "psutil",
  "typer",
  "pyyaml",
  "platformdirs",
]

[project.optional-dependencies]
dev = ["build>=1.2", "pytest>=7"]
google = [
  "google-api-python-client",
  "google-auth-httplib2",
  "google-auth-oauthlib",
  "gspread",
  "gspread-formatting",
]
gui = ["flask", "flask_sqlalchemy"]
all = ["alfrd[google,gui]"]

[project.scripts]
alfrd = "alfrd.cli:alfrd_cli"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"alfrd.gui" = [
  "templates/dashboard/*.htm",
  "static/*.css",
  "model/*.sql",
]
