"""Public compatibility classes for ALFRD's 0.2.1.0 baseline."""

from alfrd.core.project import Project, ProjectConfiguration
from alfrd.core.pipeline import (
    ArtifactRef,
    append_step_result_csv,
    BatchResult,
    ColName,
    CrashSnapshotAdapter,
    DatasetFinished,
    DatasetResult,
    DatasetStarted,
    FunctionPipelineStep,
    FunctionPipelineStepValidator,
    PipelineContext,
    PipelineCore,
    PipelineError,
    PipelineStepBase,
    PipelineStepValidatorBase,
    PipelineStepValidatorResult,
    ResultCSVAdapter,
    RunFinished,
    RunStarted,
    StepFailed,
    StepResult,
    StepSkipped,
    StepStarted,
    StepSucceeded,
    write_crash_snapshot,
)
from alfrd.core.workflow import Workflow, WorkflowConfig, WorkflowManager

__all__ = [
    "ArtifactRef",
    "append_step_result_csv",
    "BatchResult",
    "ColName",
    "CrashSnapshotAdapter",
    "DatasetFinished",
    "DatasetResult",
    "DatasetStarted",
    "FunctionPipelineStep",
    "FunctionPipelineStepValidator",
    "PipelineContext",
    "PipelineCore",
    "PipelineError",
    "PipelineStepBase",
    "PipelineStepValidatorBase",
    "PipelineStepValidatorResult",
    "Project",
    "ProjectConfiguration",
    "ResultCSVAdapter",
    "RunFinished",
    "RunStarted",
    "StepFailed",
    "StepResult",
    "StepSkipped",
    "StepStarted",
    "StepSucceeded",
    "write_crash_snapshot",
    "Workflow",
    "WorkflowConfig",
    "WorkflowManager",
]
