"""Public compatibility classes for ALFRD's 0.2.1.0 baseline."""

from alfrd.core.artifacts import (
    ArtifactError,
    ArtifactPathError,
    ArtifactTemplateError,
    KNOWN_ARTIFACT_KINDS,
    ResolvedArtifact,
    resolve_declared_artifacts,
    resolve_within_root,
)
from alfrd.core.viewers import (
    ArtifactViewerError,
    render_artifact,
    render_directory,
    render_file,
    render_gallery,
    render_html,
    render_image,
    render_json,
    render_log,
    render_table,
    render_text,
    render_yaml,
)
from alfrd.core.logframe import LogFrame, LogFrameAdapter, LogFrameEventSink
from alfrd.core.project import Project, ProjectConfiguration
from alfrd.core.pipeline import (
    ArtifactRef,
    append_step_result_csv,
    BatchResult,
    ColName,
    CrashSnapshotAdapter,
    DatasetFinished,
    DatasetResult,
    DatasetStarted,
    FunctionPipelineStep,
    FunctionPipelineStepValidator,
    PipelineContext,
    PipelineCore,
    PipelineError,
    PipelineStepBase,
    PipelineStepValidatorBase,
    PipelineStepValidatorResult,
    ResultCSVAdapter,
    RunFinished,
    RunStarted,
    StepFailed,
    StepResult,
    StepSkipped,
    StepStarted,
    StepSucceeded,
    write_crash_snapshot,
)
from alfrd.core.workflow import Workflow, WorkflowConfig, WorkflowManager
from alfrd.config import BaseConfig, CONFIG_MAPPING, Config
from alfrd.manifest import ArtifactDefinition, ProjectManifest, discover_manifest, load_manifest
from alfrd.repository import RepositoryRecord, RepositoryService

__all__ = [
    "ArtifactDefinition",
    "ArtifactError",
    "ArtifactPathError",
    "ArtifactTemplateError",
    "ArtifactViewerError",
    "BaseConfig",
    "CONFIG_MAPPING",
    "Config",
    "KNOWN_ARTIFACT_KINDS",
    "ResolvedArtifact",
    "resolve_declared_artifacts",
    "resolve_within_root",
    "render_artifact",
    "render_directory",
    "render_file",
    "render_gallery",
    "render_html",
    "render_image",
    "render_json",
    "render_log",
    "render_table",
    "render_text",
    "render_yaml",
    "ArtifactRef",
    "append_step_result_csv",
    "BatchResult",
    "ColName",
    "CrashSnapshotAdapter",
    "DatasetFinished",
    "DatasetResult",
    "DatasetStarted",
    "FunctionPipelineStep",
    "FunctionPipelineStepValidator",
    "PipelineContext",
    "PipelineCore",
    "PipelineError",
    "PipelineStepBase",
    "PipelineStepValidatorBase",
    "PipelineStepValidatorResult",
    "LogFrame",
    "LogFrameAdapter",
    "LogFrameEventSink",
    "Project",
    "ProjectManifest",
    "ProjectConfiguration",
    "RepositoryRecord",
    "RepositoryService",
    "ResultCSVAdapter",
    "RunFinished",
    "RunStarted",
    "StepFailed",
    "StepResult",
    "StepSkipped",
    "StepStarted",
    "StepSucceeded",
    "write_crash_snapshot",
    "Workflow",
    "WorkflowConfig",
    "WorkflowManager",
    "discover_manifest",
    "load_manifest",
]
